sudo: required

language: generic

git:
  depth: false

dist: xenial

cache:
  directories:
    - $HOME/.m2

services:
  - docker

before_install:
  - docker pull moussavdb/build-graalvm-amd64-linux64

script:
  - travis_retry docker run -v $PWD:/src -v $HOME/.m2:/root/.m2 moussavdb/build-graalvm-amd64-linux64 mvn clean package
